version: '3'

services:
  web:
    build: .
    command: gunicorn my_project.wsgi:application -w 4 -b 0.0.0.0:8000
    volumes:
      - static_data:/path/to/static_folder
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  static_data:
  postgres_data:
